### ISSUE TITLE
Locked .xlsx File

### ISSUE THREAD

**Issue by C00K13M3N** [jpickup/GarminTools#12] opened 2023-11-08 13:32 UTC
Hello and thank you very much for your work. I use it to quickly and easily convert training plans for several weeks from Excel (.xlsx) to Garmin Training. I have noticed that each Excel file can only be converted once. It seems that the Excel file is locked and not released anymore. Because when I copy the contents of the Excel into a new file, I can convert it again.

**Comment by jpickup** [comment] 2023-11-08 13:44
@C00K13M3N , thanks for reporting this. I'll take a look this weekend.  Can I ask a few questions first to help me reproduce the issue:
- are running the Mac or Windows version?
- does the problem only occur if the app is left running or is it a problem even when restarting the app?

**Comment by C00K13M3N** [comment] 2023-11-08 13:46
I'm running a windows version and have no oppurtunity to test it on a mac. 
The issue is taking effect in both cases, leaving it running or restarting it. 

I'm sending you the output of the log i a minute.

**Comment by jpickup** [comment] 2023-11-12 20:23
The problem here appears to be a row with blank cells that the parser is failing on. I have a fix, just need to create the builds and publish. ETA 1 hour.

**Comment by jpickup** [comment] 2023-11-12 20:56
New macOS and Windows builds are now available in the installer directory (master branch). 

Please let me know if this resolves the issue.

Thanks.

**Comment by jpickup** [comment] 2023-11-17 15:07
@C00K13M3N please let me know if the problem is solved so that I can close this issue as resolved, or if not, let me know more about the problem so I can have another go at fixing it. Thanks.

**Comment by C00K13M3N** [comment] 2023-11-20 15:14
@jpickup, thank you so much for your help! I'm happy to report that the issue has been resolved and we can now close the case. I really appreciate your hard work and dedication. Thank you again!

**Comment by jpickup** [comment] 2023-11-20 17:24
That's great news. Happy to have resolved another issue.

**Closed by jpickup** 2023-11-20 17:24 UTC
