### ISSUE TITLE
feature suggestion add step type (run, recover, warm up, ect)

### ISSUE THREAD

**Issue by mok33** [jpickup/GarminTools#8] opened 2023-10-06 07:36 UTC
Hi,
I would like to also request a feature: step type. Just like in the Garmin Connect workout creator, you select a step type: run, recover, warm up, rest, cool down. You only have the run type currently. It's nice to have it for example afterwards, you can filter the activity by step type (see image).
![WhatsApp Image 2023-10-05 at 21 24 26](https://github.com/jpickup/GarminTools/assets/31034940/f73fff38-def6-4fe5-82f0-5ca7bf14b7f3)

**Comment by jpickup** [comment] 2023-10-06 08:11
This should be achievable. It will require an additional column in the spreadsheet for the step type, that I'll make optional and that will default to Run if not present.

So far I've based everything on English, which probably isn't great for you, so I guess another feature worth adding is localisation with language packs. I'd certainly need some help with that as my knowledge French is minimal. Lower priority that this request and the other bugfix though.

**Comment by jpickup** [comment] 2023-10-06 09:27
The step type appears to be defined as the "intensity" in the Garmin API:
`package com.garmin.fit;

public enum Intensity {
    ACTIVE((short)0),
    REST((short)1),
    WARMUP((short)2),
    COOLDOWN((short)3),
    INVALID((short)255);`

Currently everything is set to Active in the app. I'll make these available as inputs.

**Comment by jpickup** [comment] 2023-10-06 10:51
This is more complicated than I thought so I'd like your help in deciding how to implement this.

My initial idea was to add a column into the spreadsheet where you could record the intensity but that doesn't make any sense as each row of the spreadsheet is a complete workout and the intensity applies individually to the steps within in. The intensity therefore can't be a column, rather it somehow needs to be included in the workout langauge.

One idea is to add some new keywords to the workout language like "Rest", "Warmup" and "Cooldown" that are used instead of a target (currently pace or hr). You would then still specify the duration with either a time or "Open". Examples could then be:
  `2:00@Warmup`
  `Open@Cooldown`
  `5:00@Rest`

An interval session might then look like:
`5:00@Warmup + (2:00@Hard + 1:00@Easy) * 10 + 5:00@Cooldown + Open@Rest`

Does that sound useful?

**Comment by mok33** [comment] 2023-10-06 10:54
That sounds better! I was also imagining something along those lines. So ACTIVE is defined as anything different than Warmup, Cooldown or Rest ?

**Comment by jpickup** [comment] 2023-10-06 10:58
I'll get working on this. Now that it's clear in my head it shouldn't be too much work. Thanks.

I actually have no idea what the impact of intensity is in the watch - is it visible during the activity? I guess I'll find out when I try it...

**Comment by mok33** [comment] 2023-10-06 11:06
The watch has a special colour display for each type of intensity. Actually, maybe Intesity can be an additional column in the Pace sheet? 
In the "enum Intensity" the item RECOVER seems to be missing.

**Comment by Abasz** [comment] 2023-10-06 11:16
> This is more complicated than I thought so I'd like your help in deciding how to implement this.
> 
> My initial idea was to add a column into the spreadsheet where you could record the intensity but that doesn't make any sense as each row of the spreadsheet is a complete workout and the intensity applies individually to the steps within in. The intensity therefore can't be a column, rather it somehow needs to be included in the workout langauge.
> 
> One idea is to add some new keywords to the workout language like "Rest", "Warmup" and "Cooldown" that are used instead of a target (currently pace or hr). You would then still specify the duration with either a time or "Open". Examples could then be: `2:00@Warmup` `Open@Cooldown` `5:00@Rest`
> 
> An interval session might then look like: `5:00@Warmup + (2:00@Hard + 1:00@Easy) * 10 + 5:00@Cooldown + Open@Rest`
> 
> Does that sound useful?

Just for you to have a perspective on this. When I did my own implementation of this I went with this approach and it has been working for many month without an issue `5:00@Warmup + (2:00@Hard + 1:00@Easy) * 10 + 5:00@Cooldown + Open@Rest`

Only I use pipe instead of @ as the @ in my language is used for the actual target speed/intensity or named target. 
This is running and with pace target:
5:00|warmup + (20:00@4:10-4:30/km|run + 1:00|recovery)*2 + lap.button|cooldown

This is bikeing with power as target (if no Intensity type is added, then it default to run/bike):
lap.button|warmup + (1:00@135-170w)*6 + 4:00|recovery + (1:00@145-175W)*5 + 3:00|recovery +(1:00@155-180w)*4 + 2:00|recovery + (1:00@165-185w)*3 + 2:00|recovery + (1:00@185-205w)*2 + 2:00|recovery + 1:00 + lap.button|cooldown

Note that these warmup, recovery etc. are only used by Garmin to differentiate the intensity type, but separately you can add the actually target speed. So I think in your language you will need one additional layer where you can add the target type

**Comment by jpickup** [comment] 2023-10-06 11:23
Thanks, very helpful. I think you have come up with a good solution.

**Comment by jpickup** [comment] 2023-10-06 14:50
@mok33 this is now implemented using the suggestion from @Abasz. The reason Recovery was missing is that I was using quite an old FIT.jar from Garmin (many years old) so I've updated to the latest version. I've not had a chance to test that everything still works, so at this stage I have not merged the changes back to the master branch. Please look at the feature/intensity branch and use the installer from there.

The format is as suggested by @Abasz, i.e. any step can be annotated with a | followed by Active/Warmup/Cooldown/Rest/Recovery an example might then be:
`Open@Easy|Warmup + (3:00@VO2Max90 +   1:00@VeryEasy|Recovery + 2:00@VO2Max95 + 1:00@VeryEasy|Recovery + 1:00@VO2Max + 1:00@VeryEasy|Recovery)  * 2 + Open@VeryEasy|Cooldown`

Any step that's not got an intensity added is assumed to be Active.

I tried this on the watch and didn't really see much difference. I have however verified that the FIT files have the correct data so I'm fairly confident the app is doing the right thing.

If everything looks good then please let me know and I'll merge all this back into master. The only reason I'm holding off from doing that is that I've not had a chance to regression test everything and am a little uncomfortable having moved to a much newer Garmin fit.jar.

**Comment by jpickup** [comment] 2023-10-06 15:32
Just noticed that I'd not pushed the installer back to github. That's been done now.

**Closed** 2023-10-12 18:41 UTC
